---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Ollama
  systemd:
    name: ollama
    state: restarted

- name: Restart Ollama exporter
  systemd:
    name: ollama-exporter
    state: restarted